spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/videgrenier221}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

firebase:
  enabled: ${FIREBASE_ENABLED:false}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:}
  api-key: ${CLOUDINARY_API_KEY:}
  api-secret: ${CLOUDINARY_API_SECRET:}
